export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './authController.serviceInterface';
export * from './episodeRatingController.service';
import { EpisodeRatingControllerService } from './episodeRatingController.service';
export * from './episodeRatingController.serviceInterface';
export * from './favoriteController.service';
import { FavoriteControllerService } from './favoriteController.service';
export * from './favoriteController.serviceInterface';
export * from './mediaStateController.service';
import { MediaStateControllerService } from './mediaStateController.service';
export * from './mediaStateController.serviceInterface';
export * from './ratingController.service';
import { RatingControllerService } from './ratingController.service';
export * from './ratingController.serviceInterface';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './userController.serviceInterface';
export * from './userListController.service';
import { UserListControllerService } from './userListController.service';
export * from './userListController.serviceInterface';
export * from './userListItemController.service';
import { UserListItemControllerService } from './userListItemController.service';
export * from './userListItemController.serviceInterface';
export * from './watchlistController.service';
import { WatchlistControllerService } from './watchlistController.service';
export * from './watchlistController.serviceInterface';
export const APIS = [AuthControllerService, EpisodeRatingControllerService, FavoriteControllerService, MediaStateControllerService, RatingControllerService, UserControllerService, UserListControllerService, UserListItemControllerService, WatchlistControllerService];
