/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthResponse } from '../model/models';
import { LoginRequest } from '../model/models';
import { RegisterRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface LoginRequestParams {
    loginRequest: LoginRequest;
}

export interface RegisterRequestParams {
    registerRequest: RegisterRequest;
}


export interface AuthControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/auth/login
* @param requestParameters
     */
    login(requestParameters: LoginRequestParams, extraHttpRequestParams?: any): Observable<AuthResponse>;

    /**
     * 
     * 
     * @endpoint post /api/auth/logout
*/
    logout(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/auth/refresh
*/
    refresh(extraHttpRequestParams?: any): Observable<AuthResponse>;

    /**
     * 
     * 
     * @endpoint post /api/auth/register
* @param requestParameters
     */
    register(requestParameters: RegisterRequestParams, extraHttpRequestParams?: any): Observable<AuthResponse>;

}
