/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EpisodeRatingRequest } from '../model/models';
import { EpisodeRatingResponse } from '../model/models';
import { PageResponseEpisodeRatingResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DeleteEpisodeRatingRequestParams {
    seriesTmdbId: number;
    seasonNumber: number;
    episodeNumber: number;
}

export interface GetEpisodeRatingRequestParams {
    seriesTmdbId: number;
    seasonNumber: number;
    episodeNumber: number;
}

export interface GetEpisodeRatingsRequestParams {
    page?: number;
    size?: number;
    sortDirection?: string;
}

export interface RateEpisodeRequestParams {
    seriesTmdbId: number;
    seasonNumber: number;
    episodeNumber: number;
    episodeRatingRequest: EpisodeRatingRequest;
}


export interface EpisodeRatingControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint delete /api/ratings/tv/{seriesTmdbId}/seasons/{seasonNumber}/episodes/{episodeNumber}
* @param requestParameters
     */
    deleteEpisodeRating(requestParameters: DeleteEpisodeRatingRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/ratings/tv/{seriesTmdbId}/seasons/{seasonNumber}/episodes/{episodeNumber}
* @param requestParameters
     */
    getEpisodeRating(requestParameters: GetEpisodeRatingRequestParams, extraHttpRequestParams?: any): Observable<EpisodeRatingResponse>;

    /**
     * 
     * 
     * @endpoint get /api/ratings/episodes
* @param requestParameters
     */
    getEpisodeRatings(requestParameters: GetEpisodeRatingsRequestParams, extraHttpRequestParams?: any): Observable<PageResponseEpisodeRatingResponse>;

    /**
     * 
     * 
     * @endpoint put /api/ratings/tv/{seriesTmdbId}/seasons/{seasonNumber}/episodes/{episodeNumber}
* @param requestParameters
     */
    rateEpisode(requestParameters: RateEpisodeRequestParams, extraHttpRequestParams?: any): Observable<EpisodeRatingResponse>;

}
