/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { EpisodeRatingRequest } from '../model/episodeRatingRequest';
// @ts-ignore
import { EpisodeRatingResponse } from '../model/episodeRatingResponse';
// @ts-ignore
import { PageResponseEpisodeRatingResponse } from '../model/pageResponseEpisodeRatingResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    EpisodeRatingControllerServiceInterface,
    DeleteEpisodeRatingRequestParams,
    GetEpisodeRatingRequestParams,
    GetEpisodeRatingsRequestParams,
    RateEpisodeRequestParams
} from './episodeRatingController.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class EpisodeRatingControllerService extends BaseService implements EpisodeRatingControllerServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @endpoint delete /api/ratings/tv/{seriesTmdbId}/seasons/{seasonNumber}/episodes/{episodeNumber}
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public deleteEpisodeRating(requestParameters: DeleteEpisodeRatingRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public deleteEpisodeRating(requestParameters: DeleteEpisodeRatingRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public deleteEpisodeRating(requestParameters: DeleteEpisodeRatingRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public deleteEpisodeRating(requestParameters: DeleteEpisodeRatingRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const seriesTmdbId = requestParameters?.seriesTmdbId;
        if (seriesTmdbId === null || seriesTmdbId === undefined) {
            throw new Error('Required parameter seriesTmdbId was null or undefined when calling deleteEpisodeRating.');
        }
        const seasonNumber = requestParameters?.seasonNumber;
        if (seasonNumber === null || seasonNumber === undefined) {
            throw new Error('Required parameter seasonNumber was null or undefined when calling deleteEpisodeRating.');
        }
        const episodeNumber = requestParameters?.episodeNumber;
        if (episodeNumber === null || episodeNumber === undefined) {
            throw new Error('Required parameter episodeNumber was null or undefined when calling deleteEpisodeRating.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/ratings/tv/${this.configuration.encodeParam({name: "seriesTmdbId", value: seriesTmdbId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/seasons/${this.configuration.encodeParam({name: "seasonNumber", value: seasonNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/episodes/${this.configuration.encodeParam({name: "episodeNumber", value: episodeNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint get /api/ratings/tv/{seriesTmdbId}/seasons/{seasonNumber}/episodes/{episodeNumber}
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getEpisodeRating(requestParameters: GetEpisodeRatingRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<EpisodeRatingResponse>;
    public getEpisodeRating(requestParameters: GetEpisodeRatingRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EpisodeRatingResponse>>;
    public getEpisodeRating(requestParameters: GetEpisodeRatingRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EpisodeRatingResponse>>;
    public getEpisodeRating(requestParameters: GetEpisodeRatingRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const seriesTmdbId = requestParameters?.seriesTmdbId;
        if (seriesTmdbId === null || seriesTmdbId === undefined) {
            throw new Error('Required parameter seriesTmdbId was null or undefined when calling getEpisodeRating.');
        }
        const seasonNumber = requestParameters?.seasonNumber;
        if (seasonNumber === null || seasonNumber === undefined) {
            throw new Error('Required parameter seasonNumber was null or undefined when calling getEpisodeRating.');
        }
        const episodeNumber = requestParameters?.episodeNumber;
        if (episodeNumber === null || episodeNumber === undefined) {
            throw new Error('Required parameter episodeNumber was null or undefined when calling getEpisodeRating.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/ratings/tv/${this.configuration.encodeParam({name: "seriesTmdbId", value: seriesTmdbId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/seasons/${this.configuration.encodeParam({name: "seasonNumber", value: seasonNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/episodes/${this.configuration.encodeParam({name: "episodeNumber", value: episodeNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EpisodeRatingResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint get /api/ratings/episodes
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getEpisodeRatings(requestParameters?: GetEpisodeRatingsRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PageResponseEpisodeRatingResponse>;
    public getEpisodeRatings(requestParameters?: GetEpisodeRatingsRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PageResponseEpisodeRatingResponse>>;
    public getEpisodeRatings(requestParameters?: GetEpisodeRatingsRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PageResponseEpisodeRatingResponse>>;
    public getEpisodeRatings(requestParameters?: GetEpisodeRatingsRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const page = requestParameters?.page;
        const size = requestParameters?.size;
        const sortDirection = requestParameters?.sortDirection;

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'page',
            <any>page,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'size',
            <any>size,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'sortDirection',
            <any>sortDirection,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/ratings/episodes`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PageResponseEpisodeRatingResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @endpoint put /api/ratings/tv/{seriesTmdbId}/seasons/{seasonNumber}/episodes/{episodeNumber}
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public rateEpisode(requestParameters: RateEpisodeRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<EpisodeRatingResponse>;
    public rateEpisode(requestParameters: RateEpisodeRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EpisodeRatingResponse>>;
    public rateEpisode(requestParameters: RateEpisodeRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EpisodeRatingResponse>>;
    public rateEpisode(requestParameters: RateEpisodeRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const seriesTmdbId = requestParameters?.seriesTmdbId;
        if (seriesTmdbId === null || seriesTmdbId === undefined) {
            throw new Error('Required parameter seriesTmdbId was null or undefined when calling rateEpisode.');
        }
        const seasonNumber = requestParameters?.seasonNumber;
        if (seasonNumber === null || seasonNumber === undefined) {
            throw new Error('Required parameter seasonNumber was null or undefined when calling rateEpisode.');
        }
        const episodeNumber = requestParameters?.episodeNumber;
        if (episodeNumber === null || episodeNumber === undefined) {
            throw new Error('Required parameter episodeNumber was null or undefined when calling rateEpisode.');
        }
        const episodeRatingRequest = requestParameters?.episodeRatingRequest;
        if (episodeRatingRequest === null || episodeRatingRequest === undefined) {
            throw new Error('Required parameter episodeRatingRequest was null or undefined when calling rateEpisode.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/ratings/tv/${this.configuration.encodeParam({name: "seriesTmdbId", value: seriesTmdbId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/seasons/${this.configuration.encodeParam({name: "seasonNumber", value: seasonNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/episodes/${this.configuration.encodeParam({name: "episodeNumber", value: episodeNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EpisodeRatingResponse>('put', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: episodeRatingRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
