/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FavoriteItemRequest } from '../model/models';
import { FavoriteItemResponse } from '../model/models';
import { PageResponseFavoriteItemResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddToFavoritesRequestParams {
    favoriteItemRequest: FavoriteItemRequest;
}

export interface GetFavoritesRequestParams {
    mediaType?: 'movie' | 'tv';
    page?: number;
    size?: number;
    sortDirection?: string;
}

export interface RemoveFromFavoritesRequestParams {
    mediaType: 'movie' | 'tv';
    tmdbId: number;
}


export interface FavoriteControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/favorites
* @param requestParameters
     */
    addToFavorites(requestParameters: AddToFavoritesRequestParams, extraHttpRequestParams?: any): Observable<FavoriteItemResponse>;

    /**
     * 
     * 
     * @endpoint get /api/favorites
* @param requestParameters
     */
    getFavorites(requestParameters: GetFavoritesRequestParams, extraHttpRequestParams?: any): Observable<PageResponseFavoriteItemResponse>;

    /**
     * 
     * 
     * @endpoint delete /api/favorites/{mediaType}/{tmdbId}
* @param requestParameters
     */
    removeFromFavorites(requestParameters: RemoveFromFavoritesRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
