/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MediaStateResponse } from '../model/models';
import { MediaStatesResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetMediaStateRequestParams {
    mediaType: 'movie' | 'tv';
    tmdbId: number;
}

export interface GetMediaStatesRequestParams {
    movieIds?: Array<number>;
    tvIds?: Array<number>;
}


export interface MediaStateControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/media/{mediaType}/{tmdbId}/state
* @param requestParameters
     */
    getMediaState(requestParameters: GetMediaStateRequestParams, extraHttpRequestParams?: any): Observable<MediaStateResponse>;

    /**
     * 
     * 
     * @endpoint get /api/media/state
* @param requestParameters
     */
    getMediaStates(requestParameters: GetMediaStatesRequestParams, extraHttpRequestParams?: any): Observable<MediaStatesResponse>;

}
