/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ListItemRequest } from '../model/models';
import { UpdateListItemRequest } from '../model/models';
import { UserListItemResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddItemRequestParams {
    listId: number;
    listItemRequest: ListItemRequest;
}

export interface ClearItemsRequestParams {
    listId: number;
}

export interface RemoveItemRequestParams {
    listId: number;
    mediaType: 'movie' | 'tv';
    tmdbId: number;
}

export interface UpdateItemRequestParams {
    listId: number;
    mediaType: 'movie' | 'tv';
    tmdbId: number;
    updateListItemRequest: UpdateListItemRequest;
}


export interface UserListItemControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/lists/{listId}/items
* @param requestParameters
     */
    addItem(requestParameters: AddItemRequestParams, extraHttpRequestParams?: any): Observable<UserListItemResponse>;

    /**
     * 
     * 
     * @endpoint delete /api/lists/{listId}/items
* @param requestParameters
     */
    clearItems(requestParameters: ClearItemsRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint delete /api/lists/{listId}/items/{mediaType}/{tmdbId}
* @param requestParameters
     */
    removeItem(requestParameters: RemoveItemRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint put /api/lists/{listId}/items/{mediaType}/{tmdbId}
* @param requestParameters
     */
    updateItem(requestParameters: UpdateItemRequestParams, extraHttpRequestParams?: any): Observable<UserListItemResponse>;

}
