/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PageResponseWatchlistItemResponse } from '../model/models';
import { WatchlistItemRequest } from '../model/models';
import { WatchlistItemResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddToWatchlistRequestParams {
    watchlistItemRequest: WatchlistItemRequest;
}

export interface GetWatchlistRequestParams {
    mediaType?: 'movie' | 'tv';
    page?: number;
    size?: number;
    sortDirection?: string;
}

export interface RemoveFromWatchlistRequestParams {
    mediaType: 'movie' | 'tv';
    tmdbId: number;
}


export interface WatchlistControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/watchlist
* @param requestParameters
     */
    addToWatchlist(requestParameters: AddToWatchlistRequestParams, extraHttpRequestParams?: any): Observable<WatchlistItemResponse>;

    /**
     * 
     * 
     * @endpoint get /api/watchlist
* @param requestParameters
     */
    getWatchlist(requestParameters: GetWatchlistRequestParams, extraHttpRequestParams?: any): Observable<PageResponseWatchlistItemResponse>;

    /**
     * 
     * 
     * @endpoint delete /api/watchlist/{mediaType}/{tmdbId}
* @param requestParameters
     */
    removeFromWatchlist(requestParameters: RemoveFromWatchlistRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
