/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccountAddFavoriteRequest } from '../model/models';
import { AccountDetails } from '../model/models';
import { AccountListPage } from '../model/models';
import { MoviePage } from '../model/models';
import { RatedMoviePage } from '../model/models';
import { RatedTvEpisodePage } from '../model/models';
import { RatedTvSeriesPage } from '../model/models';
import { StatusResponse } from '../model/models';
import { TvSeriesPage } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AccountAddFavoriteRequestParams {
    accountId: number;
    sessionId?: string;
    accountAddFavoriteRequest?: AccountAddFavoriteRequest;
}

export interface AccountAddToWatchlistRequestParams {
    accountId: number;
    sessionId?: string;
    accountAddFavoriteRequest?: AccountAddFavoriteRequest;
}

export interface AccountDetailsRequestParams {
    accountId: number;
    sessionId?: string;
}

export interface AccountFavoriteTvRequestParams {
    accountId: number;
    language?: string;
    page?: number;
    sessionId?: string;
    sortBy?: 'created_at.asc' | 'created_at.desc';
}

export interface AccountGetFavoritesRequestParams {
    accountId: number;
    language?: string;
    page?: number;
    sessionId?: string;
    sortBy?: 'created_at.asc' | 'created_at.desc';
}

export interface AccountListsRequestParams {
    accountId: number;
    page?: number;
    sessionId?: string;
}

export interface AccountRatedMoviesRequestParams {
    accountId: number;
    language?: string;
    page?: number;
    sessionId?: string;
    sortBy?: 'created_at.asc' | 'created_at.desc';
}

export interface AccountRatedTvRequestParams {
    accountId: number;
    language?: string;
    page?: number;
    sessionId?: string;
    sortBy?: 'created_at.asc' | 'created_at.desc';
}

export interface AccountRatedTvEpisodesRequestParams {
    accountId: number;
    language?: string;
    page?: number;
    sessionId?: string;
    sortBy?: 'created_at.asc' | 'created_at.desc';
}

export interface AccountWatchlistMoviesRequestParams {
    accountId: number;
    language?: string;
    page?: number;
    sessionId?: string;
    sortBy?: 'created_at.asc' | 'created_at.desc';
}

export interface AccountWatchlistTvRequestParams {
    accountId: number;
    language?: string;
    page?: number;
    sessionId?: string;
    sortBy?: 'created_at.asc' | 'created_at.desc';
}


export interface AccountRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Add Favorite
     * Mark a movie or TV show as a favourite.
     * @endpoint post /account/{account_id}/favorite
* @param requestParameters
     */
    accountAddFavorite(requestParameters: AccountAddFavoriteRequestParams, extraHttpRequestParams?: any): Observable<StatusResponse>;

    /**
     * Add To Watchlist
     * Add a movie or TV show to your watchlist.
     * @endpoint post /account/{account_id}/watchlist
* @param requestParameters
     */
    accountAddToWatchlist(requestParameters: AccountAddToWatchlistRequestParams, extraHttpRequestParams?: any): Observable<StatusResponse>;

    /**
     * Details
     * Get the public details of an account on TMDB.
     * @endpoint get /account/{account_id}
* @param requestParameters
     */
    accountDetails(requestParameters: AccountDetailsRequestParams, extraHttpRequestParams?: any): Observable<AccountDetails>;

    /**
     * Favorite TV
     * Get a users list of favourite TV shows.
     * @endpoint get /account/{account_id}/favorite/tv
* @param requestParameters
     */
    accountFavoriteTv(requestParameters: AccountFavoriteTvRequestParams, extraHttpRequestParams?: any): Observable<TvSeriesPage>;

    /**
     * Favorite Movies
     * Get a users list of favourite movies.
     * @endpoint get /account/{account_id}/favorite/movies
* @param requestParameters
     */
    accountGetFavorites(requestParameters: AccountGetFavoritesRequestParams, extraHttpRequestParams?: any): Observable<MoviePage>;

    /**
     * Lists
     * Get a users list of custom lists.
     * @endpoint get /account/{account_id}/lists
* @param requestParameters
     */
    accountLists(requestParameters: AccountListsRequestParams, extraHttpRequestParams?: any): Observable<AccountListPage>;

    /**
     * Rated Movies
     * Get a users list of rated movies.
     * @endpoint get /account/{account_id}/rated/movies
* @param requestParameters
     */
    accountRatedMovies(requestParameters: AccountRatedMoviesRequestParams, extraHttpRequestParams?: any): Observable<RatedMoviePage>;

    /**
     * Rated TV
     * Get a users list of rated TV shows.
     * @endpoint get /account/{account_id}/rated/tv
* @param requestParameters
     */
    accountRatedTv(requestParameters: AccountRatedTvRequestParams, extraHttpRequestParams?: any): Observable<RatedTvSeriesPage>;

    /**
     * Rated TV Episodes
     * Get a users list of rated TV episodes.
     * @endpoint get /account/{account_id}/rated/tv/episodes
* @param requestParameters
     */
    accountRatedTvEpisodes(requestParameters: AccountRatedTvEpisodesRequestParams, extraHttpRequestParams?: any): Observable<RatedTvEpisodePage>;

    /**
     * Watchlist Movies
     * Get a list of movies added to a users watchlist.
     * @endpoint get /account/{account_id}/watchlist/movies
* @param requestParameters
     */
    accountWatchlistMovies(requestParameters: AccountWatchlistMoviesRequestParams, extraHttpRequestParams?: any): Observable<MoviePage>;

    /**
     * Watchlist TV
     * Get a list of TV shows added to a users watchlist.
     * @endpoint get /account/{account_id}/watchlist/tv
* @param requestParameters
     */
    accountWatchlistTv(requestParameters: AccountWatchlistTvRequestParams, extraHttpRequestParams?: any): Observable<TvSeriesPage>;

}
