/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CollectionDetails } from '../model/models';
import { CollectionImages } from '../model/models';
import { TranslationList } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CollectionDetailsRequestParams {
    collectionId: number;
    language?: string;
}

export interface CollectionImagesRequestParams {
    collectionId: number;
    includeImageLanguage?: string;
    language?: string;
}

export interface CollectionTranslationsRequestParams {
    collectionId: number;
}


export interface CollectionRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Details
     * Get collection details by ID.
     * @endpoint get /collection/{collection_id}
* @param requestParameters
     */
    collectionDetails(requestParameters: CollectionDetailsRequestParams, extraHttpRequestParams?: any): Observable<CollectionDetails>;

    /**
     * Images
     * Get the images that belong to a collection.
     * @endpoint get /collection/{collection_id}/images
* @param requestParameters
     */
    collectionImages(requestParameters: CollectionImagesRequestParams, extraHttpRequestParams?: any): Observable<CollectionImages>;

    /**
     * Translations
     * 
     * @endpoint get /collection/{collection_id}/translations
* @param requestParameters
     */
    collectionTranslations(requestParameters: CollectionTranslationsRequestParams, extraHttpRequestParams?: any): Observable<TranslationList>;

}
