/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AlternativeNameList } from '../model/models';
import { CompanyDetails } from '../model/models';
import { CompanyImages } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CompanyAlternativeNamesRequestParams {
    companyId: number;
}

export interface CompanyDetailsRequestParams {
    companyId: number;
}

export interface CompanyImagesRequestParams {
    companyId: number;
}


export interface CompanyRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Alternative Names
     * Get the company details by ID.
     * @endpoint get /company/{company_id}/alternative_names
* @param requestParameters
     */
    companyAlternativeNames(requestParameters: CompanyAlternativeNamesRequestParams, extraHttpRequestParams?: any): Observable<AlternativeNameList>;

    /**
     * Details
     * Get the company details by ID.
     * @endpoint get /company/{company_id}
* @param requestParameters
     */
    companyDetails(requestParameters: CompanyDetailsRequestParams, extraHttpRequestParams?: any): Observable<CompanyDetails>;

    /**
     * Images
     * Get the company logos by id.
     * @endpoint get /company/{company_id}/images
* @param requestParameters
     */
    companyImages(requestParameters: CompanyImagesRequestParams, extraHttpRequestParams?: any): Observable<CompanyImages>;

}
