/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreditDetails } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreditDetailsRequestParams {
    creditId: string;
    language?: string;
}


export interface CreditRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Details
     * Get a movie or TV credit details by ID.
     * @endpoint get /credit/{credit_id}
* @param requestParameters
     */
    creditDetails(requestParameters: CreditDetailsRequestParams, extraHttpRequestParams?: any): Observable<CreditDetails>;

}
