/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MoviePage } from '../model/models';
import { TvSeriesPage } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DiscoverMovieRequestParams {
    certification?: string;
    certificationGte?: string;
    certificationLte?: string;
    certificationCountry?: string;
    includeAdult?: boolean;
    includeVideo?: boolean;
    language?: string;
    page?: number;
    primaryReleaseYear?: number;
    primaryReleaseDateGte?: string;
    primaryReleaseDateLte?: string;
    region?: string;
    releaseDateGte?: string;
    releaseDateLte?: string;
    sortBy?: 'original_title.asc' | 'original_title.desc' | 'popularity.asc' | 'popularity.desc' | 'revenue.asc' | 'revenue.desc' | 'primary_release_date.asc' | 'title.asc' | 'title.desc' | 'primary_release_date.desc' | 'vote_average.asc' | 'vote_average.desc' | 'vote_count.asc' | 'vote_count.desc';
    voteAverageGte?: number;
    voteAverageLte?: number;
    voteCountGte?: number;
    voteCountLte?: number;
    watchRegion?: string;
    withCast?: string;
    withCompanies?: string;
    withCrew?: string;
    withGenres?: string;
    withKeywords?: string;
    withOriginCountry?: string;
    withOriginalLanguage?: string;
    withPeople?: string;
    withReleaseType?: number;
    withRuntimeGte?: number;
    withRuntimeLte?: number;
    withWatchMonetizationTypes?: string;
    withWatchProviders?: string;
    withoutCompanies?: string;
    withoutGenres?: string;
    withoutKeywords?: string;
    withoutWatchProviders?: string;
    year?: number;
}

export interface DiscoverTvRequestParams {
    airDateGte?: string;
    airDateLte?: string;
    firstAirDateYear?: number;
    firstAirDateGte?: string;
    firstAirDateLte?: string;
    includeAdult?: boolean;
    includeNullFirstAirDates?: boolean;
    language?: string;
    page?: number;
    screenedTheatrically?: boolean;
    sortBy?: 'first_air_date.asc' | 'first_air_date.desc' | 'name.asc' | 'name.desc' | 'original_name.asc' | 'original_name.desc' | 'popularity.asc' | 'popularity.desc' | 'vote_average.asc' | 'vote_average.desc' | 'vote_count.asc' | 'vote_count.desc';
    timezone?: string;
    voteAverageGte?: number;
    voteAverageLte?: number;
    voteCountGte?: number;
    voteCountLte?: number;
    watchRegion?: string;
    withCompanies?: string;
    withGenres?: string;
    withKeywords?: string;
    withNetworks?: number;
    withOriginCountry?: string;
    withOriginalLanguage?: string;
    withRuntimeGte?: number;
    withRuntimeLte?: number;
    withStatus?: string;
    withWatchMonetizationTypes?: string;
    withWatchProviders?: string;
    withoutCompanies?: string;
    withoutGenres?: string;
    withoutKeywords?: string;
    withoutWatchProviders?: string;
    withType?: string;
}


export interface DiscoverRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Movie
     * Find movies using over 30 filters and sort options.
     * @endpoint get /discover/movie
* @param requestParameters
     */
    discoverMovie(requestParameters: DiscoverMovieRequestParams, extraHttpRequestParams?: any): Observable<MoviePage>;

    /**
     * TV
     * Find TV shows using over 30 filters and sort options.
     * @endpoint get /discover/tv
* @param requestParameters
     */
    discoverTv(requestParameters: DiscoverTvRequestParams, extraHttpRequestParams?: any): Observable<TvSeriesPage>;

}
