/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { MoviePage } from '../model/moviePage';
// @ts-ignore
import { TvSeriesPage } from '../model/tvSeriesPage';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    DiscoverRestControllerServiceInterface,
    DiscoverMovieRequestParams,
    DiscoverTvRequestParams
} from './discover.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class DiscoverRestControllerService extends BaseService implements DiscoverRestControllerServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Movie
     * Find movies using over 30 filters and sort options.
     * @endpoint get /discover/movie
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public discoverMovie(requestParameters?: DiscoverMovieRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<MoviePage>;
    public discoverMovie(requestParameters?: DiscoverMovieRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<MoviePage>>;
    public discoverMovie(requestParameters?: DiscoverMovieRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<MoviePage>>;
    public discoverMovie(requestParameters?: DiscoverMovieRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const certification = requestParameters?.certification;
        const certificationGte = requestParameters?.certificationGte;
        const certificationLte = requestParameters?.certificationLte;
        const certificationCountry = requestParameters?.certificationCountry;
        const includeAdult = requestParameters?.includeAdult;
        const includeVideo = requestParameters?.includeVideo;
        const language = requestParameters?.language;
        const page = requestParameters?.page;
        const primaryReleaseYear = requestParameters?.primaryReleaseYear;
        const primaryReleaseDateGte = requestParameters?.primaryReleaseDateGte;
        const primaryReleaseDateLte = requestParameters?.primaryReleaseDateLte;
        const region = requestParameters?.region;
        const releaseDateGte = requestParameters?.releaseDateGte;
        const releaseDateLte = requestParameters?.releaseDateLte;
        const sortBy = requestParameters?.sortBy;
        const voteAverageGte = requestParameters?.voteAverageGte;
        const voteAverageLte = requestParameters?.voteAverageLte;
        const voteCountGte = requestParameters?.voteCountGte;
        const voteCountLte = requestParameters?.voteCountLte;
        const watchRegion = requestParameters?.watchRegion;
        const withCast = requestParameters?.withCast;
        const withCompanies = requestParameters?.withCompanies;
        const withCrew = requestParameters?.withCrew;
        const withGenres = requestParameters?.withGenres;
        const withKeywords = requestParameters?.withKeywords;
        const withOriginCountry = requestParameters?.withOriginCountry;
        const withOriginalLanguage = requestParameters?.withOriginalLanguage;
        const withPeople = requestParameters?.withPeople;
        const withReleaseType = requestParameters?.withReleaseType;
        const withRuntimeGte = requestParameters?.withRuntimeGte;
        const withRuntimeLte = requestParameters?.withRuntimeLte;
        const withWatchMonetizationTypes = requestParameters?.withWatchMonetizationTypes;
        const withWatchProviders = requestParameters?.withWatchProviders;
        const withoutCompanies = requestParameters?.withoutCompanies;
        const withoutGenres = requestParameters?.withoutGenres;
        const withoutKeywords = requestParameters?.withoutKeywords;
        const withoutWatchProviders = requestParameters?.withoutWatchProviders;
        const year = requestParameters?.year;

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'certification',
            <any>certification,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'certification.gte',
            <any>certificationGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'certification.lte',
            <any>certificationLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'certification_country',
            <any>certificationCountry,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'include_adult',
            <any>includeAdult,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'include_video',
            <any>includeVideo,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'language',
            <any>language,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'page',
            <any>page,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'primary_release_year',
            <any>primaryReleaseYear,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'primary_release_date.gte',
            <any>primaryReleaseDateGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'primary_release_date.lte',
            <any>primaryReleaseDateLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'region',
            <any>region,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'release_date.gte',
            <any>releaseDateGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'release_date.lte',
            <any>releaseDateLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'sort_by',
            <any>sortBy,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_average.gte',
            <any>voteAverageGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_average.lte',
            <any>voteAverageLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_count.gte',
            <any>voteCountGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_count.lte',
            <any>voteCountLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'watch_region',
            <any>watchRegion,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_cast',
            <any>withCast,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_companies',
            <any>withCompanies,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_crew',
            <any>withCrew,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_genres',
            <any>withGenres,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_keywords',
            <any>withKeywords,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_origin_country',
            <any>withOriginCountry,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_original_language',
            <any>withOriginalLanguage,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_people',
            <any>withPeople,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_release_type',
            <any>withReleaseType,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_runtime.gte',
            <any>withRuntimeGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_runtime.lte',
            <any>withRuntimeLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_watch_monetization_types',
            <any>withWatchMonetizationTypes,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_watch_providers',
            <any>withWatchProviders,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_companies',
            <any>withoutCompanies,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_genres',
            <any>withoutGenres,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_keywords',
            <any>withoutKeywords,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_watch_providers',
            <any>withoutWatchProviders,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'year',
            <any>year,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/discover/movie`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<MoviePage>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * TV
     * Find TV shows using over 30 filters and sort options.
     * @endpoint get /discover/tv
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public discoverTv(requestParameters?: DiscoverTvRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<TvSeriesPage>;
    public discoverTv(requestParameters?: DiscoverTvRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<TvSeriesPage>>;
    public discoverTv(requestParameters?: DiscoverTvRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<TvSeriesPage>>;
    public discoverTv(requestParameters?: DiscoverTvRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const airDateGte = requestParameters?.airDateGte;
        const airDateLte = requestParameters?.airDateLte;
        const firstAirDateYear = requestParameters?.firstAirDateYear;
        const firstAirDateGte = requestParameters?.firstAirDateGte;
        const firstAirDateLte = requestParameters?.firstAirDateLte;
        const includeAdult = requestParameters?.includeAdult;
        const includeNullFirstAirDates = requestParameters?.includeNullFirstAirDates;
        const language = requestParameters?.language;
        const page = requestParameters?.page;
        const screenedTheatrically = requestParameters?.screenedTheatrically;
        const sortBy = requestParameters?.sortBy;
        const timezone = requestParameters?.timezone;
        const voteAverageGte = requestParameters?.voteAverageGte;
        const voteAverageLte = requestParameters?.voteAverageLte;
        const voteCountGte = requestParameters?.voteCountGte;
        const voteCountLte = requestParameters?.voteCountLte;
        const watchRegion = requestParameters?.watchRegion;
        const withCompanies = requestParameters?.withCompanies;
        const withGenres = requestParameters?.withGenres;
        const withKeywords = requestParameters?.withKeywords;
        const withNetworks = requestParameters?.withNetworks;
        const withOriginCountry = requestParameters?.withOriginCountry;
        const withOriginalLanguage = requestParameters?.withOriginalLanguage;
        const withRuntimeGte = requestParameters?.withRuntimeGte;
        const withRuntimeLte = requestParameters?.withRuntimeLte;
        const withStatus = requestParameters?.withStatus;
        const withWatchMonetizationTypes = requestParameters?.withWatchMonetizationTypes;
        const withWatchProviders = requestParameters?.withWatchProviders;
        const withoutCompanies = requestParameters?.withoutCompanies;
        const withoutGenres = requestParameters?.withoutGenres;
        const withoutKeywords = requestParameters?.withoutKeywords;
        const withoutWatchProviders = requestParameters?.withoutWatchProviders;
        const withType = requestParameters?.withType;

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'air_date.gte',
            <any>airDateGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'air_date.lte',
            <any>airDateLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'first_air_date_year',
            <any>firstAirDateYear,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'first_air_date.gte',
            <any>firstAirDateGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'first_air_date.lte',
            <any>firstAirDateLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'include_adult',
            <any>includeAdult,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'include_null_first_air_dates',
            <any>includeNullFirstAirDates,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'language',
            <any>language,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'page',
            <any>page,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'screened_theatrically',
            <any>screenedTheatrically,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'sort_by',
            <any>sortBy,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'timezone',
            <any>timezone,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_average.gte',
            <any>voteAverageGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_average.lte',
            <any>voteAverageLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_count.gte',
            <any>voteCountGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_count.lte',
            <any>voteCountLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'watch_region',
            <any>watchRegion,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_companies',
            <any>withCompanies,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_genres',
            <any>withGenres,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_keywords',
            <any>withKeywords,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_networks',
            <any>withNetworks,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_origin_country',
            <any>withOriginCountry,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_original_language',
            <any>withOriginalLanguage,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_runtime.gte',
            <any>withRuntimeGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_runtime.lte',
            <any>withRuntimeLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_status',
            <any>withStatus,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_watch_monetization_types',
            <any>withWatchMonetizationTypes,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_watch_providers',
            <any>withWatchProviders,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_companies',
            <any>withoutCompanies,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_genres',
            <any>withoutGenres,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_keywords',
            <any>withoutKeywords,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_watch_providers',
            <any>withoutWatchProviders,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_type',
            <any>withType,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/discover/tv`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<TvSeriesPage>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
