/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Keyword } from '../model/models';
import { KeywordMoviePage } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface KeywordDetailsRequestParams {
    keywordId: number;
}

export interface KeywordMoviesRequestParams {
    keywordId: string;
    includeAdult?: boolean;
    language?: string;
    page?: number;
}


export interface KeywordRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Details
     * 
     * @endpoint get /keyword/{keyword_id}
* @param requestParameters
     */
    keywordDetails(requestParameters: KeywordDetailsRequestParams, extraHttpRequestParams?: any): Observable<Keyword>;

    /**
     * Movies
     * 
     * @endpoint get /keyword/{keyword_id}/movies
* @param requestParameters
     */
    keywordMovies(requestParameters: KeywordMoviesRequestParams, extraHttpRequestParams?: any): Observable<KeywordMoviePage>;

}
