/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccountAddFavoriteRequest } from '../model/models';
import { AccountStates } from '../model/models';
import { AlternativeTitleList } from '../model/models';
import { ChangeList } from '../model/models';
import { Credits } from '../model/models';
import { ExternalIds } from '../model/models';
import { ImageList } from '../model/models';
import { KeywordList } from '../model/models';
import { Movie } from '../model/models';
import { MovieListPage } from '../model/models';
import { MoviePage } from '../model/models';
import { ReleaseDateList } from '../model/models';
import { ReviewPage } from '../model/models';
import { StatusResponse } from '../model/models';
import { TranslationList } from '../model/models';
import { VideoList } from '../model/models';
import { WatchProviderList } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface MovieAccountStatesRequestParams {
    movieId: number;
    sessionId?: string;
    guestSessionId?: string;
}

export interface MovieAddRatingRequestParams {
    movieId: number;
    contentType: string;
    guestSessionId?: string;
    sessionId?: string;
    accountAddFavoriteRequest?: AccountAddFavoriteRequest;
}

export interface MovieAlternativeTitlesRequestParams {
    movieId: number;
    country?: string;
}

export interface MovieChangesRequestParams {
    movieId: number;
    endDate?: string;
    page?: number;
    startDate?: string;
}

export interface MovieCreditsRequestParams {
    movieId: number;
    language?: string;
}

export interface MovieDeleteRatingRequestParams {
    movieId: number;
    contentType?: string;
    guestSessionId?: string;
    sessionId?: string;
}

export interface MovieDetailsRequestParams {
    movieId: number;
    appendToResponse?: string;
    language?: string;
    sessionId?: string;
    guestSessionId?: string;
}

export interface MovieExternalIdsRequestParams {
    movieId: number;
}

export interface MovieImagesRequestParams {
    movieId: number;
    includeImageLanguage?: string;
    language?: string;
}

export interface MovieKeywordsRequestParams {
    movieId: string;
}

export interface MovieListsRequestParams {
    movieId: number;
    language?: string;
    page?: number;
}

export interface MovieRecommendationsRequestParams {
    movieId: number;
    language?: string;
    page?: number;
}

export interface MovieReleaseDatesRequestParams {
    movieId: number;
}

export interface MovieReviewsRequestParams {
    movieId: number;
    language?: string;
    page?: number;
}

export interface MovieSimilarRequestParams {
    movieId: number;
    language?: string;
    page?: number;
}

export interface MovieTranslationsRequestParams {
    movieId: number;
}

export interface MovieVideosRequestParams {
    movieId: number;
    language?: string;
}

export interface MovieWatchProvidersRequestParams {
    movieId: number;
}


export interface MovieRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Account States
     * Get the rating, watchlist and favourite status of an account.
     * @endpoint get /movie/{movie_id}/account_states
* @param requestParameters
     */
    movieAccountStates(requestParameters: MovieAccountStatesRequestParams, extraHttpRequestParams?: any): Observable<AccountStates>;

    /**
     * Add Rating
     * Rate a movie and save it to your rated list.
     * @endpoint post /movie/{movie_id}/rating
* @param requestParameters
     */
    movieAddRating(requestParameters: MovieAddRatingRequestParams, extraHttpRequestParams?: any): Observable<StatusResponse>;

    /**
     * Alternative Titles
     * Get the alternative titles for a movie.
     * @endpoint get /movie/{movie_id}/alternative_titles
* @param requestParameters
     */
    movieAlternativeTitles(requestParameters: MovieAlternativeTitlesRequestParams, extraHttpRequestParams?: any): Observable<AlternativeTitleList>;

    /**
     * Changes
     * Get the recent changes for a movie.
     * @endpoint get /movie/{movie_id}/changes
* @param requestParameters
     */
    movieChanges(requestParameters: MovieChangesRequestParams, extraHttpRequestParams?: any): Observable<ChangeList>;

    /**
     * Credits
     * 
     * @endpoint get /movie/{movie_id}/credits
* @param requestParameters
     */
    movieCredits(requestParameters: MovieCreditsRequestParams, extraHttpRequestParams?: any): Observable<Credits>;

    /**
     * Delete Rating
     * Delete a user rating.
     * @endpoint delete /movie/{movie_id}/rating
* @param requestParameters
     */
    movieDeleteRating(requestParameters: MovieDeleteRatingRequestParams, extraHttpRequestParams?: any): Observable<StatusResponse>;

    /**
     * Details
     * Get the top level details of a movie by ID.
     * @endpoint get /movie/{movie_id}
* @param requestParameters
     */
    movieDetails(requestParameters: MovieDetailsRequestParams, extraHttpRequestParams?: any): Observable<Movie>;

    /**
     * External IDs
     * 
     * @endpoint get /movie/{movie_id}/external_ids
* @param requestParameters
     */
    movieExternalIds(requestParameters: MovieExternalIdsRequestParams, extraHttpRequestParams?: any): Observable<ExternalIds>;

    /**
     * Images
     * Get the images that belong to a movie.
     * @endpoint get /movie/{movie_id}/images
* @param requestParameters
     */
    movieImages(requestParameters: MovieImagesRequestParams, extraHttpRequestParams?: any): Observable<ImageList>;

    /**
     * Keywords
     * 
     * @endpoint get /movie/{movie_id}/keywords
* @param requestParameters
     */
    movieKeywords(requestParameters: MovieKeywordsRequestParams, extraHttpRequestParams?: any): Observable<KeywordList>;

    /**
     * Lists
     * Get the lists that a movie has been added to.
     * @endpoint get /movie/{movie_id}/lists
* @param requestParameters
     */
    movieLists(requestParameters: MovieListsRequestParams, extraHttpRequestParams?: any): Observable<MovieListPage>;

    /**
     * Recommendations
     * 
     * @endpoint get /movie/{movie_id}/recommendations
* @param requestParameters
     */
    movieRecommendations(requestParameters: MovieRecommendationsRequestParams, extraHttpRequestParams?: any): Observable<MoviePage>;

    /**
     * Release Dates
     * Get the release dates and certifications for a movie.
     * @endpoint get /movie/{movie_id}/release_dates
* @param requestParameters
     */
    movieReleaseDates(requestParameters: MovieReleaseDatesRequestParams, extraHttpRequestParams?: any): Observable<ReleaseDateList>;

    /**
     * Reviews
     * Get the user reviews for a movie.
     * @endpoint get /movie/{movie_id}/reviews
* @param requestParameters
     */
    movieReviews(requestParameters: MovieReviewsRequestParams, extraHttpRequestParams?: any): Observable<ReviewPage>;

    /**
     * Similar
     * Get the similar movies based on genres and keywords.
     * @endpoint get /movie/{movie_id}/similar
* @param requestParameters
     */
    movieSimilar(requestParameters: MovieSimilarRequestParams, extraHttpRequestParams?: any): Observable<MoviePage>;

    /**
     * Translations
     * Get the translations for a movie.
     * @endpoint get /movie/{movie_id}/translations
* @param requestParameters
     */
    movieTranslations(requestParameters: MovieTranslationsRequestParams, extraHttpRequestParams?: any): Observable<TranslationList>;

    /**
     * Videos
     * 
     * @endpoint get /movie/{movie_id}/videos
* @param requestParameters
     */
    movieVideos(requestParameters: MovieVideosRequestParams, extraHttpRequestParams?: any): Observable<VideoList>;

    /**
     * Watch Providers
     * Get the list of streaming providers we have for a movie.
     * @endpoint get /movie/{movie_id}/watch/providers
* @param requestParameters
     */
    movieWatchProviders(requestParameters: MovieWatchProvidersRequestParams, extraHttpRequestParams?: any): Observable<WatchProviderList>;

}
