/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AlternativeNameList } from '../model/models';
import { NetworkDetails } from '../model/models';
import { NetworkImages } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AlternativeNamesCopyRequestParams {
    networkId: number;
}

export interface DetailsCopyRequestParams {
    networkId: number;
}

export interface NetworkDetailsRequestParams {
    networkId: number;
}


export interface NetworkRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Images
     * Get the TV network logos by id.
     * @endpoint get /network/{network_id}/images
* @param requestParameters
     */
    alternativeNamesCopy(requestParameters: AlternativeNamesCopyRequestParams, extraHttpRequestParams?: any): Observable<NetworkImages>;

    /**
     * Alternative Names
     * Get the alternative names of a network.
     * @endpoint get /network/{network_id}/alternative_names
* @param requestParameters
     */
    detailsCopy(requestParameters: DetailsCopyRequestParams, extraHttpRequestParams?: any): Observable<AlternativeNameList>;

    /**
     * Details
     * 
     * @endpoint get /network/{network_id}
* @param requestParameters
     */
    networkDetails(requestParameters: NetworkDetailsRequestParams, extraHttpRequestParams?: any): Observable<NetworkDetails>;

}
