/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChangeList } from '../model/models';
import { Person } from '../model/models';
import { PersonCombinedCredits } from '../model/models';
import { PersonExternalIds } from '../model/models';
import { PersonImages } from '../model/models';
import { PersonMovieCredits } from '../model/models';
import { PersonTranslationList } from '../model/models';
import { PersonTvCredits } from '../model/models';
import { TaggedImagePage } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface PersonChangesRequestParams {
    personId: number;
    endDate?: string;
    page?: number;
    startDate?: string;
}

export interface PersonCombinedCreditsRequestParams {
    personId: string;
    language?: string;
}

export interface PersonDetailsRequestParams {
    personId: number;
    appendToResponse?: string;
    language?: string;
}

export interface PersonExternalIdsRequestParams {
    personId: number;
}

export interface PersonImagesRequestParams {
    personId: number;
}

export interface PersonMovieCreditsRequestParams {
    personId: number;
    language?: string;
}

export interface PersonTaggedImagesRequestParams {
    personId: number;
    page?: number;
}

export interface PersonTvCreditsRequestParams {
    personId: number;
    language?: string;
}

export interface TranslationsRequestParams {
    personId: number;
}


export interface PersonRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Changes
     * Get the recent changes for a person.
     * @endpoint get /person/{person_id}/changes
* @param requestParameters
     */
    personChanges(requestParameters: PersonChangesRequestParams, extraHttpRequestParams?: any): Observable<ChangeList>;

    /**
     * Combined Credits
     * Get the combined movie and TV credits that belong to a person.
     * @endpoint get /person/{person_id}/combined_credits
* @param requestParameters
     */
    personCombinedCredits(requestParameters: PersonCombinedCreditsRequestParams, extraHttpRequestParams?: any): Observable<PersonCombinedCredits>;

    /**
     * Details
     * Query the top level details of a person.
     * @endpoint get /person/{person_id}
* @param requestParameters
     */
    personDetails(requestParameters: PersonDetailsRequestParams, extraHttpRequestParams?: any): Observable<Person>;

    /**
     * External IDs
     * Get the external ID\&#39;s that belong to a person.
     * @endpoint get /person/{person_id}/external_ids
* @param requestParameters
     */
    personExternalIds(requestParameters: PersonExternalIdsRequestParams, extraHttpRequestParams?: any): Observable<PersonExternalIds>;

    /**
     * Images
     * Get the profile images that belong to a person.
     * @endpoint get /person/{person_id}/images
* @param requestParameters
     */
    personImages(requestParameters: PersonImagesRequestParams, extraHttpRequestParams?: any): Observable<PersonImages>;

    /**
     * Movie Credits
     * Get the movie credits for a person.
     * @endpoint get /person/{person_id}/movie_credits
* @param requestParameters
     */
    personMovieCredits(requestParameters: PersonMovieCreditsRequestParams, extraHttpRequestParams?: any): Observable<PersonMovieCredits>;

    /**
     * Tagged Images
     * Get the tagged images for a person.
     * @endpoint get /person/{person_id}/tagged_images
* @param requestParameters
     */
    personTaggedImages(requestParameters: PersonTaggedImagesRequestParams, extraHttpRequestParams?: any): Observable<TaggedImagePage>;

    /**
     * TV Credits
     * Get the TV credits that belong to a person.
     * @endpoint get /person/{person_id}/tv_credits
* @param requestParameters
     */
    personTvCredits(requestParameters: PersonTvCreditsRequestParams, extraHttpRequestParams?: any): Observable<PersonTvCredits>;

    /**
     * Translations
     * Get the translations that belong to a person.
     * @endpoint get /person/{person_id}/translations
* @param requestParameters
     */
    translations(requestParameters: TranslationsRequestParams, extraHttpRequestParams?: any): Observable<PersonTranslationList>;

}
