/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CollectionPage } from '../model/models';
import { CompanyPage } from '../model/models';
import { KeywordPage } from '../model/models';
import { MoviePage } from '../model/models';
import { MultiPage } from '../model/models';
import { PersonPage } from '../model/models';
import { TvSeriesPage } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface SearchCollectionRequestParams {
    query: string;
    includeAdult?: boolean;
    language?: string;
    page?: number;
    region?: string;
}

export interface SearchCompanyRequestParams {
    query: string;
    page?: number;
}

export interface SearchKeywordRequestParams {
    query: string;
    page?: number;
}

export interface SearchMovieRequestParams {
    query: string;
    includeAdult?: boolean;
    language?: string;
    primaryReleaseYear?: string;
    page?: number;
    region?: string;
    year?: string;
}

export interface SearchMultiRequestParams {
    query: string;
    includeAdult?: boolean;
    language?: string;
    page?: number;
}

export interface SearchPersonRequestParams {
    query: string;
    includeAdult?: boolean;
    language?: string;
    page?: number;
}

export interface SearchTvRequestParams {
    query: string;
    firstAirDateYear?: number;
    includeAdult?: boolean;
    language?: string;
    page?: number;
    year?: number;
}


export interface SearchRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Collection
     * Search for collections by their original, translated and alternative names.
     * @endpoint get /search/collection
* @param requestParameters
     */
    searchCollection(requestParameters: SearchCollectionRequestParams, extraHttpRequestParams?: any): Observable<CollectionPage>;

    /**
     * Company
     * Search for companies by their original and alternative names.
     * @endpoint get /search/company
* @param requestParameters
     */
    searchCompany(requestParameters: SearchCompanyRequestParams, extraHttpRequestParams?: any): Observable<CompanyPage>;

    /**
     * Keyword
     * Search for keywords by their name.
     * @endpoint get /search/keyword
* @param requestParameters
     */
    searchKeyword(requestParameters: SearchKeywordRequestParams, extraHttpRequestParams?: any): Observable<KeywordPage>;

    /**
     * Movie
     * Search for movies by their original, translated and alternative titles.
     * @endpoint get /search/movie
* @param requestParameters
     */
    searchMovie(requestParameters: SearchMovieRequestParams, extraHttpRequestParams?: any): Observable<MoviePage>;

    /**
     * Multi
     * Use multi search when you want to search for movies, TV shows and people in a single request.
     * @endpoint get /search/multi
* @param requestParameters
     */
    searchMulti(requestParameters: SearchMultiRequestParams, extraHttpRequestParams?: any): Observable<MultiPage>;

    /**
     * Person
     * Search for people by their name and also known as names.
     * @endpoint get /search/person
* @param requestParameters
     */
    searchPerson(requestParameters: SearchPersonRequestParams, extraHttpRequestParams?: any): Observable<PersonPage>;

    /**
     * TV
     * Search for TV shows by their original, translated and also known as names.
     * @endpoint get /search/tv
* @param requestParameters
     */
    searchTv(requestParameters: SearchTvRequestParams, extraHttpRequestParams?: any): Observable<TvSeriesPage>;

}
