/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { AccountAddFavoriteRequest } from '../model/accountAddFavoriteRequest';
// @ts-ignore
import { AccountStates } from '../model/accountStates';
// @ts-ignore
import { ChangeList } from '../model/changeList';
// @ts-ignore
import { StatusResponse } from '../model/statusResponse';
// @ts-ignore
import { TranslationList } from '../model/translationList';
// @ts-ignore
import { TvEpisode } from '../model/tvEpisode';
// @ts-ignore
import { TvEpisodeCredits } from '../model/tvEpisodeCredits';
// @ts-ignore
import { TvEpisodeExternalIds } from '../model/tvEpisodeExternalIds';
// @ts-ignore
import { TvEpisodeImages } from '../model/tvEpisodeImages';
// @ts-ignore
import { VideoList } from '../model/videoList';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    TvEpisodeRestControllerServiceInterface,
    TvEpisodeAccountStatesRequestParams,
    TvEpisodeAddRatingRequestParams,
    TvEpisodeChangesByIdRequestParams,
    TvEpisodeCreditsRequestParams,
    TvEpisodeDeleteRatingRequestParams,
    TvEpisodeDetailsRequestParams,
    TvEpisodeExternalIdsRequestParams,
    TvEpisodeImagesRequestParams,
    TvEpisodeTranslationsRequestParams,
    TvEpisodeVideosRequestParams
} from './tvEpisode.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class TvEpisodeRestControllerService extends BaseService implements TvEpisodeRestControllerServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Account States
     * Get the rating, watchlist and favourite status.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/account_states
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public tvEpisodeAccountStates(requestParameters: TvEpisodeAccountStatesRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<AccountStates>;
    public tvEpisodeAccountStates(requestParameters: TvEpisodeAccountStatesRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AccountStates>>;
    public tvEpisodeAccountStates(requestParameters: TvEpisodeAccountStatesRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AccountStates>>;
    public tvEpisodeAccountStates(requestParameters: TvEpisodeAccountStatesRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const seriesId = requestParameters?.seriesId;
        if (seriesId === null || seriesId === undefined) {
            throw new Error('Required parameter seriesId was null or undefined when calling tvEpisodeAccountStates.');
        }
        const seasonNumber = requestParameters?.seasonNumber;
        if (seasonNumber === null || seasonNumber === undefined) {
            throw new Error('Required parameter seasonNumber was null or undefined when calling tvEpisodeAccountStates.');
        }
        const episodeNumber = requestParameters?.episodeNumber;
        if (episodeNumber === null || episodeNumber === undefined) {
            throw new Error('Required parameter episodeNumber was null or undefined when calling tvEpisodeAccountStates.');
        }
        const sessionId = requestParameters?.sessionId;
        const guestSessionId = requestParameters?.guestSessionId;

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'session_id',
            <any>sessionId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'guest_session_id',
            <any>guestSessionId,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/tv/${this.configuration.encodeParam({name: "seriesId", value: seriesId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/season/${this.configuration.encodeParam({name: "seasonNumber", value: seasonNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/episode/${this.configuration.encodeParam({name: "episodeNumber", value: episodeNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/account_states`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AccountStates>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Add Rating
     * Rate a TV episode and save it to your rated list.
     * @endpoint post /tv/{series_id}/season/{season_number}/episode/{episode_number}/rating
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public tvEpisodeAddRating(requestParameters: TvEpisodeAddRatingRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<StatusResponse>;
    public tvEpisodeAddRating(requestParameters: TvEpisodeAddRatingRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<StatusResponse>>;
    public tvEpisodeAddRating(requestParameters: TvEpisodeAddRatingRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<StatusResponse>>;
    public tvEpisodeAddRating(requestParameters: TvEpisodeAddRatingRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const seriesId = requestParameters?.seriesId;
        if (seriesId === null || seriesId === undefined) {
            throw new Error('Required parameter seriesId was null or undefined when calling tvEpisodeAddRating.');
        }
        const contentType = requestParameters?.contentType;
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling tvEpisodeAddRating.');
        }
        const seasonNumber = requestParameters?.seasonNumber;
        if (seasonNumber === null || seasonNumber === undefined) {
            throw new Error('Required parameter seasonNumber was null or undefined when calling tvEpisodeAddRating.');
        }
        const episodeNumber = requestParameters?.episodeNumber;
        if (episodeNumber === null || episodeNumber === undefined) {
            throw new Error('Required parameter episodeNumber was null or undefined when calling tvEpisodeAddRating.');
        }
        const guestSessionId = requestParameters?.guestSessionId;
        const sessionId = requestParameters?.sessionId;
        const accountAddFavoriteRequest = requestParameters?.accountAddFavoriteRequest;

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'guest_session_id',
            <any>guestSessionId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'session_id',
            <any>sessionId,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;
        if (contentType !== undefined && contentType !== null) {
            localVarHeaders = localVarHeaders.set('Content-Type', String(contentType));
        }

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/tv/${this.configuration.encodeParam({name: "seriesId", value: seriesId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/season/${this.configuration.encodeParam({name: "seasonNumber", value: seasonNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/episode/${this.configuration.encodeParam({name: "episodeNumber", value: episodeNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/rating`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<StatusResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: accountAddFavoriteRequest,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Changes
     * Get the recent changes for a TV episode.
     * @endpoint get /tv/episode/{episode_id}/changes
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public tvEpisodeChangesById(requestParameters: TvEpisodeChangesByIdRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ChangeList>;
    public tvEpisodeChangesById(requestParameters: TvEpisodeChangesByIdRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ChangeList>>;
    public tvEpisodeChangesById(requestParameters: TvEpisodeChangesByIdRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ChangeList>>;
    public tvEpisodeChangesById(requestParameters: TvEpisodeChangesByIdRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const episodeId = requestParameters?.episodeId;
        if (episodeId === null || episodeId === undefined) {
            throw new Error('Required parameter episodeId was null or undefined when calling tvEpisodeChangesById.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/tv/episode/${this.configuration.encodeParam({name: "episodeId", value: episodeId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/changes`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ChangeList>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Credits
     * 
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/credits
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public tvEpisodeCredits(requestParameters: TvEpisodeCreditsRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<TvEpisodeCredits>;
    public tvEpisodeCredits(requestParameters: TvEpisodeCreditsRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<TvEpisodeCredits>>;
    public tvEpisodeCredits(requestParameters: TvEpisodeCreditsRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<TvEpisodeCredits>>;
    public tvEpisodeCredits(requestParameters: TvEpisodeCreditsRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const seriesId = requestParameters?.seriesId;
        if (seriesId === null || seriesId === undefined) {
            throw new Error('Required parameter seriesId was null or undefined when calling tvEpisodeCredits.');
        }
        const seasonNumber = requestParameters?.seasonNumber;
        if (seasonNumber === null || seasonNumber === undefined) {
            throw new Error('Required parameter seasonNumber was null or undefined when calling tvEpisodeCredits.');
        }
        const episodeNumber = requestParameters?.episodeNumber;
        if (episodeNumber === null || episodeNumber === undefined) {
            throw new Error('Required parameter episodeNumber was null or undefined when calling tvEpisodeCredits.');
        }
        const language = requestParameters?.language;

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'language',
            <any>language,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/tv/${this.configuration.encodeParam({name: "seriesId", value: seriesId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/season/${this.configuration.encodeParam({name: "seasonNumber", value: seasonNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/episode/${this.configuration.encodeParam({name: "episodeNumber", value: episodeNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/credits`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<TvEpisodeCredits>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete Rating
     * Delete your rating on a TV episode.
     * @endpoint delete /tv/{series_id}/season/{season_number}/episode/{episode_number}/rating
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public tvEpisodeDeleteRating(requestParameters: TvEpisodeDeleteRatingRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<StatusResponse>;
    public tvEpisodeDeleteRating(requestParameters: TvEpisodeDeleteRatingRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<StatusResponse>>;
    public tvEpisodeDeleteRating(requestParameters: TvEpisodeDeleteRatingRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<StatusResponse>>;
    public tvEpisodeDeleteRating(requestParameters: TvEpisodeDeleteRatingRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const seriesId = requestParameters?.seriesId;
        if (seriesId === null || seriesId === undefined) {
            throw new Error('Required parameter seriesId was null or undefined when calling tvEpisodeDeleteRating.');
        }
        const seasonNumber = requestParameters?.seasonNumber;
        if (seasonNumber === null || seasonNumber === undefined) {
            throw new Error('Required parameter seasonNumber was null or undefined when calling tvEpisodeDeleteRating.');
        }
        const episodeNumber = requestParameters?.episodeNumber;
        if (episodeNumber === null || episodeNumber === undefined) {
            throw new Error('Required parameter episodeNumber was null or undefined when calling tvEpisodeDeleteRating.');
        }
        const contentType = requestParameters?.contentType;
        const guestSessionId = requestParameters?.guestSessionId;
        const sessionId = requestParameters?.sessionId;

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'guest_session_id',
            <any>guestSessionId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'session_id',
            <any>sessionId,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;
        if (contentType !== undefined && contentType !== null) {
            localVarHeaders = localVarHeaders.set('Content-Type', String(contentType));
        }

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/tv/${this.configuration.encodeParam({name: "seriesId", value: seriesId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/season/${this.configuration.encodeParam({name: "seasonNumber", value: seasonNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/episode/${this.configuration.encodeParam({name: "episodeNumber", value: episodeNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/rating`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<StatusResponse>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Details
     * Query the details of a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public tvEpisodeDetails(requestParameters: TvEpisodeDetailsRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<TvEpisode>;
    public tvEpisodeDetails(requestParameters: TvEpisodeDetailsRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<TvEpisode>>;
    public tvEpisodeDetails(requestParameters: TvEpisodeDetailsRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<TvEpisode>>;
    public tvEpisodeDetails(requestParameters: TvEpisodeDetailsRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const seriesId = requestParameters?.seriesId;
        if (seriesId === null || seriesId === undefined) {
            throw new Error('Required parameter seriesId was null or undefined when calling tvEpisodeDetails.');
        }
        const seasonNumber = requestParameters?.seasonNumber;
        if (seasonNumber === null || seasonNumber === undefined) {
            throw new Error('Required parameter seasonNumber was null or undefined when calling tvEpisodeDetails.');
        }
        const episodeNumber = requestParameters?.episodeNumber;
        if (episodeNumber === null || episodeNumber === undefined) {
            throw new Error('Required parameter episodeNumber was null or undefined when calling tvEpisodeDetails.');
        }
        const appendToResponse = requestParameters?.appendToResponse;
        const language = requestParameters?.language;

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'append_to_response',
            <any>appendToResponse,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'language',
            <any>language,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/tv/${this.configuration.encodeParam({name: "seriesId", value: seriesId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/season/${this.configuration.encodeParam({name: "seasonNumber", value: seasonNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/episode/${this.configuration.encodeParam({name: "episodeNumber", value: episodeNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<TvEpisode>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * External IDs
     * Get a list of external IDs that have been added to a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/external_ids
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public tvEpisodeExternalIds(requestParameters: TvEpisodeExternalIdsRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<TvEpisodeExternalIds>;
    public tvEpisodeExternalIds(requestParameters: TvEpisodeExternalIdsRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<TvEpisodeExternalIds>>;
    public tvEpisodeExternalIds(requestParameters: TvEpisodeExternalIdsRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<TvEpisodeExternalIds>>;
    public tvEpisodeExternalIds(requestParameters: TvEpisodeExternalIdsRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const seriesId = requestParameters?.seriesId;
        if (seriesId === null || seriesId === undefined) {
            throw new Error('Required parameter seriesId was null or undefined when calling tvEpisodeExternalIds.');
        }
        const seasonNumber = requestParameters?.seasonNumber;
        if (seasonNumber === null || seasonNumber === undefined) {
            throw new Error('Required parameter seasonNumber was null or undefined when calling tvEpisodeExternalIds.');
        }
        const episodeNumber = requestParameters?.episodeNumber;
        if (episodeNumber === null || episodeNumber === undefined) {
            throw new Error('Required parameter episodeNumber was null or undefined when calling tvEpisodeExternalIds.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/tv/${this.configuration.encodeParam({name: "seriesId", value: seriesId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/season/${this.configuration.encodeParam({name: "seasonNumber", value: seasonNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/episode/${this.configuration.encodeParam({name: "episodeNumber", value: episodeNumber, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/external_ids`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<TvEpisodeExternalIds>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Images
     * Get the images that belong to a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/images
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public tvEpisodeImages(requestParameters: TvEpisodeImagesRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<TvEpisodeImages>;
    public tvEpisodeImages(requestParameters: TvEpisodeImagesRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<TvEpisodeImages>>;
    public tvEpisodeImages(requestParameters: TvEpisodeImagesRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<TvEpisodeImages>>;
    public tvEpisodeImages(requestParameters: TvEpisodeImagesRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const seriesId = requestParameters?.seriesId;
        if (seriesId === null || seriesId === undefined) {
            throw new Error('Required parameter seriesId was null or undefined when calling tvEpisodeImages.');
        }
        const seasonNumber = requestParameters?.seasonNumber;
        if (seasonNumber === null || seasonNumber === undefined) {
            throw new Error('Required parameter seasonNumber was null or undefined when calling tvEpisodeImages.');
        }
        const episodeNumber = requestParameters?.episodeNumber;
        if (episodeNumber === null || episodeNumber === undefined) {
            throw new Error('Required parameter episodeNumber was null or undefined when calling tvEpisodeImages.');
        }
        const includeImageLanguage = requestParameters?.includeImageLanguage;
        const language = requestParameters?.language;

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'include_image_language',
            <any>includeImageLanguage,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'language',
            <any>language,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/tv/${this.configuration.encodeParam({name: "seriesId", value: seriesId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/season/${this.configuration.encodeParam({name: "seasonNumber", value: seasonNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/episode/${this.configuration.encodeParam({name: "episodeNumber", value: episodeNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/images`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<TvEpisodeImages>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Translations
     * Get the translations that have been added to a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/translations
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public tvEpisodeTranslations(requestParameters: TvEpisodeTranslationsRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<TranslationList>;
    public tvEpisodeTranslations(requestParameters: TvEpisodeTranslationsRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<TranslationList>>;
    public tvEpisodeTranslations(requestParameters: TvEpisodeTranslationsRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<TranslationList>>;
    public tvEpisodeTranslations(requestParameters: TvEpisodeTranslationsRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const seriesId = requestParameters?.seriesId;
        if (seriesId === null || seriesId === undefined) {
            throw new Error('Required parameter seriesId was null or undefined when calling tvEpisodeTranslations.');
        }
        const seasonNumber = requestParameters?.seasonNumber;
        if (seasonNumber === null || seasonNumber === undefined) {
            throw new Error('Required parameter seasonNumber was null or undefined when calling tvEpisodeTranslations.');
        }
        const episodeNumber = requestParameters?.episodeNumber;
        if (episodeNumber === null || episodeNumber === undefined) {
            throw new Error('Required parameter episodeNumber was null or undefined when calling tvEpisodeTranslations.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/tv/${this.configuration.encodeParam({name: "seriesId", value: seriesId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/season/${this.configuration.encodeParam({name: "seasonNumber", value: seasonNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/episode/${this.configuration.encodeParam({name: "episodeNumber", value: episodeNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/translations`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<TranslationList>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Videos
     * Get the videos that belong to a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/videos
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public tvEpisodeVideos(requestParameters: TvEpisodeVideosRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<VideoList>;
    public tvEpisodeVideos(requestParameters: TvEpisodeVideosRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<VideoList>>;
    public tvEpisodeVideos(requestParameters: TvEpisodeVideosRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<VideoList>>;
    public tvEpisodeVideos(requestParameters: TvEpisodeVideosRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const seriesId = requestParameters?.seriesId;
        if (seriesId === null || seriesId === undefined) {
            throw new Error('Required parameter seriesId was null or undefined when calling tvEpisodeVideos.');
        }
        const seasonNumber = requestParameters?.seasonNumber;
        if (seasonNumber === null || seasonNumber === undefined) {
            throw new Error('Required parameter seasonNumber was null or undefined when calling tvEpisodeVideos.');
        }
        const episodeNumber = requestParameters?.episodeNumber;
        if (episodeNumber === null || episodeNumber === undefined) {
            throw new Error('Required parameter episodeNumber was null or undefined when calling tvEpisodeVideos.');
        }
        const includeVideoLanguage = requestParameters?.includeVideoLanguage;
        const language = requestParameters?.language;

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'include_video_language',
            <any>includeVideoLanguage,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'language',
            <any>language,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/tv/${this.configuration.encodeParam({name: "seriesId", value: seriesId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/season/${this.configuration.encodeParam({name: "seasonNumber", value: seasonNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/episode/${this.configuration.encodeParam({name: "episodeNumber", value: episodeNumber, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/videos`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<VideoList>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
