/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccountAddFavoriteRequest } from '../model/models';
import { AccountStates } from '../model/models';
import { ChangeList } from '../model/models';
import { StatusResponse } from '../model/models';
import { TranslationList } from '../model/models';
import { TvEpisode } from '../model/models';
import { TvEpisodeCredits } from '../model/models';
import { TvEpisodeExternalIds } from '../model/models';
import { TvEpisodeImages } from '../model/models';
import { VideoList } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface TvEpisodeAccountStatesRequestParams {
    seriesId: number;
    seasonNumber: number;
    episodeNumber: number;
    sessionId?: string;
    guestSessionId?: string;
}

export interface TvEpisodeAddRatingRequestParams {
    seriesId: number;
    contentType: string;
    seasonNumber: number;
    episodeNumber: number;
    guestSessionId?: string;
    sessionId?: string;
    accountAddFavoriteRequest?: AccountAddFavoriteRequest;
}

export interface TvEpisodeChangesByIdRequestParams {
    episodeId: number;
}

export interface TvEpisodeCreditsRequestParams {
    seriesId: number;
    seasonNumber: number;
    episodeNumber: number;
    language?: string;
}

export interface TvEpisodeDeleteRatingRequestParams {
    seriesId: number;
    seasonNumber: number;
    episodeNumber: number;
    contentType?: string;
    guestSessionId?: string;
    sessionId?: string;
}

export interface TvEpisodeDetailsRequestParams {
    seriesId: number;
    seasonNumber: number;
    episodeNumber: number;
    appendToResponse?: string;
    language?: string;
}

export interface TvEpisodeExternalIdsRequestParams {
    seriesId: number;
    seasonNumber: number;
    episodeNumber: string;
}

export interface TvEpisodeImagesRequestParams {
    seriesId: number;
    seasonNumber: number;
    episodeNumber: number;
    includeImageLanguage?: string;
    language?: string;
}

export interface TvEpisodeTranslationsRequestParams {
    seriesId: number;
    seasonNumber: number;
    episodeNumber: number;
}

export interface TvEpisodeVideosRequestParams {
    seriesId: number;
    seasonNumber: number;
    episodeNumber: number;
    includeVideoLanguage?: string;
    language?: string;
}


export interface TvEpisodeRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Account States
     * Get the rating, watchlist and favourite status.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/account_states
* @param requestParameters
     */
    tvEpisodeAccountStates(requestParameters: TvEpisodeAccountStatesRequestParams, extraHttpRequestParams?: any): Observable<AccountStates>;

    /**
     * Add Rating
     * Rate a TV episode and save it to your rated list.
     * @endpoint post /tv/{series_id}/season/{season_number}/episode/{episode_number}/rating
* @param requestParameters
     */
    tvEpisodeAddRating(requestParameters: TvEpisodeAddRatingRequestParams, extraHttpRequestParams?: any): Observable<StatusResponse>;

    /**
     * Changes
     * Get the recent changes for a TV episode.
     * @endpoint get /tv/episode/{episode_id}/changes
* @param requestParameters
     */
    tvEpisodeChangesById(requestParameters: TvEpisodeChangesByIdRequestParams, extraHttpRequestParams?: any): Observable<ChangeList>;

    /**
     * Credits
     * 
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/credits
* @param requestParameters
     */
    tvEpisodeCredits(requestParameters: TvEpisodeCreditsRequestParams, extraHttpRequestParams?: any): Observable<TvEpisodeCredits>;

    /**
     * Delete Rating
     * Delete your rating on a TV episode.
     * @endpoint delete /tv/{series_id}/season/{season_number}/episode/{episode_number}/rating
* @param requestParameters
     */
    tvEpisodeDeleteRating(requestParameters: TvEpisodeDeleteRatingRequestParams, extraHttpRequestParams?: any): Observable<StatusResponse>;

    /**
     * Details
     * Query the details of a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}
* @param requestParameters
     */
    tvEpisodeDetails(requestParameters: TvEpisodeDetailsRequestParams, extraHttpRequestParams?: any): Observable<TvEpisode>;

    /**
     * External IDs
     * Get a list of external IDs that have been added to a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/external_ids
* @param requestParameters
     */
    tvEpisodeExternalIds(requestParameters: TvEpisodeExternalIdsRequestParams, extraHttpRequestParams?: any): Observable<TvEpisodeExternalIds>;

    /**
     * Images
     * Get the images that belong to a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/images
* @param requestParameters
     */
    tvEpisodeImages(requestParameters: TvEpisodeImagesRequestParams, extraHttpRequestParams?: any): Observable<TvEpisodeImages>;

    /**
     * Translations
     * Get the translations that have been added to a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/translations
* @param requestParameters
     */
    tvEpisodeTranslations(requestParameters: TvEpisodeTranslationsRequestParams, extraHttpRequestParams?: any): Observable<TranslationList>;

    /**
     * Videos
     * Get the videos that belong to a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/videos
* @param requestParameters
     */
    tvEpisodeVideos(requestParameters: TvEpisodeVideosRequestParams, extraHttpRequestParams?: any): Observable<VideoList>;

}
