/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EpisodeGroupDetails } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface TvEpisodeGroupDetailsRequestParams {
    tvEpisodeGroupId: string;
}


export interface TvEpisodeGroupRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Details
     * Get the details of a TV episode group.
     * @endpoint get /tv/episode_group/{tv_episode_group_id}
* @param requestParameters
     */
    tvEpisodeGroupDetails(requestParameters: TvEpisodeGroupDetailsRequestParams, extraHttpRequestParams?: any): Observable<EpisodeGroupDetails>;

}
