/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { TvSeries } from '../model/models';
import { TvSeriesPage } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface TvSeriesAiringTodayListRequestParams {
    language?: string;
    page?: number;
    timezone?: string;
}

export interface TvSeriesOnTheAirListRequestParams {
    language?: string;
    page?: number;
    timezone?: string;
}

export interface TvSeriesPopularListRequestParams {
    language?: string;
    page?: number;
}

export interface TvSeriesTopRatedListRequestParams {
    language?: string;
    page?: number;
}


export interface TvSeriesListRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Airing Today
     * Get a list of TV shows airing today.
     * @endpoint get /tv/airing_today
* @param requestParameters
     */
    tvSeriesAiringTodayList(requestParameters: TvSeriesAiringTodayListRequestParams, extraHttpRequestParams?: any): Observable<TvSeriesPage>;

    /**
     * Latest
     * Get the newest TV show ID.
     * @endpoint get /tv/latest
*/
    tvSeriesLatestId(extraHttpRequestParams?: any): Observable<TvSeries>;

    /**
     * On The Air
     * Get a list of TV shows that air in the next 7 days.
     * @endpoint get /tv/on_the_air
* @param requestParameters
     */
    tvSeriesOnTheAirList(requestParameters: TvSeriesOnTheAirListRequestParams, extraHttpRequestParams?: any): Observable<TvSeriesPage>;

    /**
     * Popular
     * Get a list of TV shows ordered by popularity.
     * @endpoint get /tv/popular
* @param requestParameters
     */
    tvSeriesPopularList(requestParameters: TvSeriesPopularListRequestParams, extraHttpRequestParams?: any): Observable<TvSeriesPage>;

    /**
     * Top Rated
     * Get a list of TV shows ordered by rating.
     * @endpoint get /tv/top_rated
* @param requestParameters
     */
    tvSeriesTopRatedList(requestParameters: TvSeriesTopRatedListRequestParams, extraHttpRequestParams?: any): Observable<TvSeriesPage>;

}
