/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AggregateCredits } from '../model/models';
import { ChangeList } from '../model/models';
import { Credits } from '../model/models';
import { TranslationList } from '../model/models';
import { TvSeason } from '../model/models';
import { TvSeasonAccountStates } from '../model/models';
import { TvSeasonExternalIds } from '../model/models';
import { TvSeasonImages } from '../model/models';
import { VideoList } from '../model/models';
import { WatchProviderList } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface TvSeasonAccountStatesRequestParams {
    seriesId: number;
    seasonNumber: number;
    sessionId?: string;
    guestSessionId?: string;
}

export interface TvSeasonAggregateCreditsRequestParams {
    seriesId: number;
    seasonNumber: number;
    language?: string;
}

export interface TvSeasonChangesByIdRequestParams {
    seasonId: number;
    endDate?: string;
    page?: number;
    startDate?: string;
}

export interface TvSeasonCreditsRequestParams {
    seriesId: number;
    seasonNumber: number;
    language?: string;
}

export interface TvSeasonDetailsRequestParams {
    seriesId: number;
    seasonNumber: number;
    appendToResponse?: string;
    language?: string;
}

export interface TvSeasonExternalIdsRequestParams {
    seriesId: number;
    seasonNumber: number;
}

export interface TvSeasonImagesRequestParams {
    seriesId: number;
    seasonNumber: number;
    includeImageLanguage?: string;
    language?: string;
}

export interface TvSeasonTranslationsRequestParams {
    seriesId: number;
    seasonNumber: number;
}

export interface TvSeasonVideosRequestParams {
    seriesId: number;
    seasonNumber: number;
    includeVideoLanguage?: string;
    language?: string;
}

export interface TvSeasonWatchProvidersRequestParams {
    seriesId: number;
    seasonNumber: number;
    language?: string;
}


export interface TvSeasonRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Account States
     * Get the rating, watchlist and favourite status.
     * @endpoint get /tv/{series_id}/season/{season_number}/account_states
* @param requestParameters
     */
    tvSeasonAccountStates(requestParameters: TvSeasonAccountStatesRequestParams, extraHttpRequestParams?: any): Observable<TvSeasonAccountStates>;

    /**
     * Aggregate Credits
     * Get the aggregate credits (cast and crew) that have been added to a TV season.
     * @endpoint get /tv/{series_id}/season/{season_number}/aggregate_credits
* @param requestParameters
     */
    tvSeasonAggregateCredits(requestParameters: TvSeasonAggregateCreditsRequestParams, extraHttpRequestParams?: any): Observable<AggregateCredits>;

    /**
     * Changes
     * Get the recent changes for a TV season.
     * @endpoint get /tv/season/{season_id}/changes
* @param requestParameters
     */
    tvSeasonChangesById(requestParameters: TvSeasonChangesByIdRequestParams, extraHttpRequestParams?: any): Observable<ChangeList>;

    /**
     * Credits
     * 
     * @endpoint get /tv/{series_id}/season/{season_number}/credits
* @param requestParameters
     */
    tvSeasonCredits(requestParameters: TvSeasonCreditsRequestParams, extraHttpRequestParams?: any): Observable<Credits>;

    /**
     * Details
     * Query the details of a TV season.
     * @endpoint get /tv/{series_id}/season/{season_number}
* @param requestParameters
     */
    tvSeasonDetails(requestParameters: TvSeasonDetailsRequestParams, extraHttpRequestParams?: any): Observable<TvSeason>;

    /**
     * External IDs
     * Get a list of external IDs that have been added to a TV season.
     * @endpoint get /tv/{series_id}/season/{season_number}/external_ids
* @param requestParameters
     */
    tvSeasonExternalIds(requestParameters: TvSeasonExternalIdsRequestParams, extraHttpRequestParams?: any): Observable<TvSeasonExternalIds>;

    /**
     * Images
     * Get the images that belong to a TV season.
     * @endpoint get /tv/{series_id}/season/{season_number}/images
* @param requestParameters
     */
    tvSeasonImages(requestParameters: TvSeasonImagesRequestParams, extraHttpRequestParams?: any): Observable<TvSeasonImages>;

    /**
     * Translations
     * Get the translations for a TV season.
     * @endpoint get /tv/{series_id}/season/{season_number}/translations
* @param requestParameters
     */
    tvSeasonTranslations(requestParameters: TvSeasonTranslationsRequestParams, extraHttpRequestParams?: any): Observable<TranslationList>;

    /**
     * Videos
     * Get the videos that belong to a TV season.
     * @endpoint get /tv/{series_id}/season/{season_number}/videos
* @param requestParameters
     */
    tvSeasonVideos(requestParameters: TvSeasonVideosRequestParams, extraHttpRequestParams?: any): Observable<VideoList>;

    /**
     * Watch Providers
     * Get the list of streaming providers we have for a TV season.
     * @endpoint get /tv/{series_id}/season/{season_number}/watch/providers
* @param requestParameters
     */
    tvSeasonWatchProviders(requestParameters: TvSeasonWatchProvidersRequestParams, extraHttpRequestParams?: any): Observable<WatchProviderList>;

}
