/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { WatchProviderCatalog } from '../model/models';
import { WatchProviderRegionList } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface WatchProviderTvListRequestParams {
    language?: string;
    watchRegion?: string;
}

export interface WatchProvidersAvailableRegionsRequestParams {
    language?: string;
}

export interface WatchProvidersMovieListRequestParams {
    language?: string;
    watchRegion?: string;
}


export interface WatchProviderRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * TV Providers
     * Get the list of streaming providers we have for TV shows.
     * @endpoint get /watch/providers/tv
* @param requestParameters
     */
    watchProviderTvList(requestParameters: WatchProviderTvListRequestParams, extraHttpRequestParams?: any): Observable<WatchProviderCatalog>;

    /**
     * Available Regions
     * Get the list of the countries we have watch provider (OTT/streaming) data for.
     * @endpoint get /watch/providers/regions
* @param requestParameters
     */
    watchProvidersAvailableRegions(requestParameters: WatchProvidersAvailableRegionsRequestParams, extraHttpRequestParams?: any): Observable<WatchProviderRegionList>;

    /**
     * Movie Providers
     * Get the list of streaming providers we have for movies.
     * @endpoint get /watch/providers/movie
* @param requestParameters
     */
    watchProvidersMovieList(requestParameters: WatchProvidersMovieListRequestParams, extraHttpRequestParams?: any): Observable<WatchProviderCatalog>;

}
