/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserListItemResponse } from './userListItemResponse';


export interface PageResponseUserListItemResponse { 
    content?: Array<UserListItemResponse>;
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
}

