/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListCoverRequest } from './listCoverRequest';


export interface UpdateUserListRequest { 
    name: string;
    description?: string;
    isPublic: boolean;
    sortBy: UpdateUserListRequest.SortByEnum;
    cover?: ListCoverRequest;
}
export namespace UpdateUserListRequest {
    export const SortByEnum = {
        OriginalOrderAsc: 'original_order.asc',
        OriginalOrderDesc: 'original_order.desc',
        TitleAsc: 'title.asc',
        TitleDesc: 'title.desc',
        ReleaseDateAsc: 'release_date.asc',
        ReleaseDateDesc: 'release_date.desc',
        VoteAverageAsc: 'vote_average.asc',
        VoteAverageDesc: 'vote_average.desc'
    } as const;
    export type SortByEnum = typeof SortByEnum[keyof typeof SortByEnum];
}


