/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListCoverResponse } from './listCoverResponse';


export interface UserListResponse { 
    id?: number;
    name?: string;
    description?: string;
    sortBy?: UserListResponse.SortByEnum;
    itemCount?: number;
    cover?: ListCoverResponse;
    createdAt?: string;
    updatedAt?: string;
}
export namespace UserListResponse {
    export const SortByEnum = {
        OriginalOrderAsc: 'original_order.asc',
        OriginalOrderDesc: 'original_order.desc',
        TitleAsc: 'title.asc',
        TitleDesc: 'title.desc',
        ReleaseDateAsc: 'release_date.asc',
        ReleaseDateDesc: 'release_date.desc',
        VoteAverageAsc: 'vote_average.asc',
        VoteAverageDesc: 'vote_average.desc'
    } as const;
    export type SortByEnum = typeof SortByEnum[keyof typeof SortByEnum];
}


